apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootgcp
  labels:
    app: springbootgcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springbootgcp
  template:
    metadata:
      labels:
        app: springbootgcp
    spec:
      containers:
      - name: springbootgcp
        image: gcr.io/cloudbeeswithgke/springbootgcp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springbootgcp
spec:
  selector:
    app: springbootgcp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30018
  type: LoadBalancer
  